models_to_evaluate:
  - phi_4_multimodal_instruct
datasets_to_evaluate:
  - fluencybank
max_samples_per_dataset: 5
save_samples: true
output_dir: /Users/Benjamin/dev/ssa/output/eval
batch_size: 2 # Process 2 samples at a time, set to null for one-by-one processing
